---

- name: deploy REST API service
 -hosts: webservers
  remote_user: root
  
  -name install software
   apt: 
    name:
           - git
           - python3-pip
           - python3.8 
           - python3-venv 
           - python3-virtualenv 
           - build-essential
  state: latest

-name: install Flask Flask-SQLAlchemy
pip:
 name: 
    - Flask 
    - Flask-SQLAlchemy
    
    - name: clone code
  ansible.builtin.git:
    repo: https://github.com/iaroki/omo-devops-test-task.git
    dest: /home/root
    
    name: execute install script
  script: /home/root/app.py